// Used when there's no MASSIVE_API_KEY configured (or free-tier quota is
// exhausted), so search still works for anyone trying the app out without
// signing up for anything first.
export const FALLBACK_TICKERS = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A" },
  { symbol: "AMZN", name: "Amazon.com, Inc." },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "META", name: "Meta Platforms, Inc." },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "NFLX", name: "Netflix, Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "BA", name: "The Boeing Company" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "KO", name: "The Coca-Cola Company" },
  { symbol: "PEP", name: "PepsiCo, Inc." },
  { symbol: "NKE", name: "NIKE, Inc." },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "PYPL", name: "PayPal Holdings, Inc." },
  { symbol: "UBER", name: "Uber Technologies, Inc." },
  { symbol: "ABNB", name: "Airbnb, Inc." },
  { symbol: "SPOT", name: "Spotify Technology S.A." },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "IBM", name: "International Business Machines Corporation" },
  { symbol: "GME", name: "GameStop Corp." },
  { symbol: "AMC", name: "AMC Entertainment Holdings, Inc." },
];
